services:
  flyway:
    build:
      context: .
      dockerfile: Dockerfile.flyway
    env_file:
      - ${ENV_PROPERTIES}
    volumes:
      - ./resources/migration/map_image:/flyway/output:rw
    command: migrate
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: ["migrate"]